In [1]:
import numpy as np

a=np.array([1,2,3,4])
b=np.array([10,20,30,40])

print(a)
print(b)

[1 2 3 4]
[10 20 30 40]


In [2]:
print(a+b)

[11 22 33 44]


In [3]:
print(a-b)

[ -9 -18 -27 -36]


In [4]:
print(a*5)

[ 5 10 15 20]


In [8]:
x=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(x.shape)

(3, 3)


In [7]:
print(x[:,0])

[1 4 7]


In [10]:
print(x[0, :]) 

[1 2 3]


In [11]:
print(x.mean()) 

5.0


In [12]:
print(x.mean(axis=0))

[4. 5. 6.]


In [14]:
print(x.std(axis=0))

[2.44948974 2.44948974 2.44948974]


In [15]:
x_norm=(x-x.mean(axis=0))/x.std(axis=0)
print(x_norm)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [16]:
w=np.array([[0.2],[0.4],[0.6]])
y=np.dot(x,w)
print(y)

[[ 2.8]
 [ 6.4]
 [10. ]]
